CHAPTER 2 

In [1]:
#load libraries (we might need them)
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import ISLP as book

In [2]:
#Just a print statement
print("Fit a model with", 11, "variables.")

Fit a model with 11 variables.


In [4]:
#Help command to get help on a function
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [5]:
#Addition of integers 
3+5

8

In [7]:
#String concantenation
"Hello" + " " + "World"

'Hello World'

In [ ]:
#List
x=[1,2,3]
x

[1, 2, 3]

A note from data structures

In [ ]:
x=[1,2,3]
y=x #I don't copy the list, I just create a new reference to the same list
y.append(4)
print(x)
print(y) 

[1, 2, 3, 4]
[1, 2, 3, 4]


In [10]:
y= [5,6,7]
x+y

[1, 2, 3, 4, 5, 6, 7]

NUMERICAL PYTHON

In [ ]:
#Matrices Addition
x=np.array([1,2,3])
y=np.array([4,5,6])
x+y

array([5, 7, 9])

In [16]:
x=np.array([[1,2],[3,4]])
x


array([[1, 2],
       [3, 4]])

In [18]:
#Matrix dimension
x.ndim #x is a 2D array

2

In [19]:
#data attribute 
x.dtype

dtype('int64')

In [21]:
#if at least a decimal existed in the matrix,then:
x1=np.array([[1,2],[3,4.0]])
x1.dtype

dtype('float64')

In [22]:
np.array?

Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [26]:
np.array([[1,2],[3,4]],float).dtype

dtype('float64')

In [27]:
x.shape

(2, 2)

In [28]:
x=np.array([1,2,3,4])
x.sum()

np.int64(10)

In [29]:
np.sum(x)

np.int64(10)

In [ ]:
#to return just 10 
x.sum().item()

10

In [32]:
#never forget the int() function
int(x.sum())

10

In [38]:
x=np.array([[1,2],[3,4],[5,6]])
print("og x:\n",x)
#reshape() function
x_reshaped=x.reshape(2,3)
print("reshaped x:\n",x_reshaped)

og x:
 [[1 2]
 [3 4]
 [5 6]]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [39]:
#Elements' access 
x_reshaped[0,1] #first row, second column

np.int64(2)