In [68]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

CHAPTER 2 

In [69]:
#load libraries (we might need them)
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import ISLP as book

In [70]:
#Just a print statement
print("Fit a model with", 11, "variables.")

Fit a model with 11 variables.


In [71]:
#Help command to get help on a function
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [72]:
#Addition of integers 
3+5

8

In [73]:
#String concantenation
"Hello" + " " + "World"

'Hello World'

In [74]:
#List
x=[1,2,3]
x

[1, 2, 3]

A note from data structures

In [75]:
x=[1,2,3]
y=x #I don't copy the list, I just create a new reference to the same list
y.append(4)
print(x)
print(y) 

[1, 2, 3, 4]
[1, 2, 3, 4]


In [76]:
y= [5,6,7]
x+y

[1, 2, 3, 4, 5, 6, 7]

NUMERICAL PYTHON

In [77]:
#Matrices Addition
x=np.array([1,2,3])
y=np.array([4,5,6])
x+y

array([5, 7, 9])

In [78]:
x=np.array([[1,2],[3,4]])
x


array([[1, 2],
       [3, 4]])

In [79]:
#Matrix dimension
x.ndim #x is a 2D array

2

In [80]:
#data attribute 
x.dtype

dtype('int64')

In [81]:
#if at least a decimal existed in the matrix,then:
x1=np.array([[1,2],[3,4.0]])
x1.dtype

dtype('float64')

In [82]:
np.array?

Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [83]:
np.array([[1,2],[3,4]],float).dtype

dtype('float64')

In [84]:
x.shape

(2, 2)

In [85]:
x=np.array([1,2,3,4])
x.sum()

np.int64(10)

In [86]:
np.sum(x)

np.int64(10)

In [87]:
#to return just 10 
x.sum().item()

10

In [88]:
#never forget the int() function
int(x.sum())

10

In [89]:
x=np.array([[1,2],[3,4],[5,6]])
print("og x:\n",x)
#reshape() function
x_reshaped=x.reshape(2,3)
print("reshaped x:\n",x_reshaped)

og x:
 [[1 2]
 [3 4]
 [5 6]]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [90]:
#Elements' access 
x_reshaped[0,1] #first row, second column

np.int64(2)

In [91]:
print("og x:\n",x)
print("reshaped x:\n",x_reshaped)
x_reshaped[0,0] = 999 #we change the first row, first column element of the reshaped matrix
print("reshaped x after change:\n",x_reshaped)
print("og x after reshaped change:\n",x) #the original matrix is also changed because reshaping does not create a copy of the original matrix

og x:
 [[1 2]
 [3 4]
 [5 6]]
reshaped x:
 [[1 2 3]
 [4 5 6]]
reshaped x after change:
 [[999   2   3]
 [  4   5   6]]
og x after reshaped change:
 [[999   2]
 [  3   4]
 [  5   6]]


The change in the element of x happens because we don't make a new copy of the matrix  
We use the same memory space to store them  
We can say that those are the ecos of python 


Tuples don't support item assignment

In [92]:
tuple1=(1,2,3)
tuple1[0]= 999 #tuples are immutable, so this will raise an error

TypeError: 'tuple' object does not support item assignment

In [ ]:
x_reshaped.shape
x_reshaped.ndim
x_reshaped.dtype

(2, 3)

2

dtype('int64')

In [95]:
np.sqrt(x) #we get the square root of each element in the matrix x
x**2 #we get the square of each element in the matrix x
x**0.5 #we get the square root of each element in the matrix x by using the power operator

array([[31.60696126,  1.41421356],
       [ 1.73205081,  2.        ],
       [ 2.23606798,  2.44948974]])

array([[998001,      4],
       [     9,     16],
       [    25,     36]])

array([[31.60696126,  1.41421356],
       [ 1.73205081,  2.        ],
       [ 2.23606798,  2.44948974]])